# traefik.toml

# defaultEntryPoints must be at the top because it should not be in any table below
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "ecylmz.com"
swarmmode = true
watch = true
exposedbydefault = false

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "emrecan@ecylmz.com"
storage = "/etc/acme.json"
entryPoint = "https"
onDemand = true
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "test.ecylmz.com"